"""Generate the limits CSV and per-ratio batch_metrics YAML configs for the
TEP IDV13 XMEAS10 few-shot study.

Writes:
  setting/limits_tep_xmeas10.csv                 (H/L = mu+-3sigma from Run1-7 pre-onset)
  setting/batch_metrics_tep_xmeas10_{ratio}.yaml (one per few-shot ratio)

All 15 methods share the same window grid (seq_len=96, saved pred_len=96,
1810 windows/run, 3620 total), so no align_eval_to is needed; eval_steps=15
truncates every model to the 45-min prognosis horizon. Zero-shot dirs saved
(3620, 15, 1) — row count matches, truncation is a no-op.

Run via batch_metrics_xmeas10.sh (idempotent).
"""
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

TSFM = Path("/home/aicode/sherwin/TSFM")
V5 = Path("/home/aicode/sherwin/dataset/TEP/csv_5var")
RESULTS = TSFM / "results"
TARGET = "XMEAS10 Purge Rate"
RATIOS = ["r0p01", "r0p02", "r0p05", "r0p1", "r0p25", "r0p5", "r1p0"]
FAULT_ROW = 600  # IDV13 onset at t=30 h, 0.05 h/step
DL_MODELS = ["CNNLSTM", "DiPCALSTM", "LSTMGRU", "STAConvBiLSTM", "TCNTransformer"]
LIMITS_CSV = TSFM / "setting" / "limits_tep_xmeas10.csv"


def run_csv(n: int) -> Path:
    return sorted(V5.glob(f"*IDV13*Run{n}.csv"))[0]


def write_limits() -> None:
    pre = np.concatenate([
        pd.read_csv(run_csv(n))[TARGET].to_numpy(float)[:FAULT_ROW]
        for n in range(1, 8)
    ])
    mu, sd = pre.mean(), pre.std()
    # batch_metrics.py reads high = iloc[1] (H), low = iloc[2] (L);
    # HH/LL are unused placeholders kept at mu+-4 sigma for the csv shape.
    df = pd.DataFrame(
        [[mu + 4 * sd, mu + 3 * sd, mu - 3 * sd, mu - 4 * sd]],
        index=[TARGET], columns=["HH", "H", "L", "LL"],
    )
    df.to_csv(LIMITS_CSV, float_format="%.6f")
    print(f"limits: mu={mu:.4f} sigma={sd:.5f}  "
          f"H/L=[{mu - 3 * sd:.4f}, {mu + 3 * sd:.4f}] -> {LIMITS_CSV}")


def one_dir(pattern: str, exclude: str = "_val_") -> str:
    hits = [d for d in sorted(RESULTS.glob(pattern)) if exclude not in d.name]
    if len(hits) != 1:
        raise SystemExit(f"expected 1 result dir for {pattern}, got {len(hits)}: "
                         f"{[d.name for d in hits]}")
    return hits[0].name


def model_dirs(ratio: str) -> list:
    entries = []
    for m in DL_MODELS:
        for dom in ("raw", "diff"):
            entries.append({
                "name": f"{m}-{dom}",
                "result_dir": one_dir(
                    f"long_term_forecast_TEP_IDV13_XMEAS10_5var_{dom}_{m}_{ratio}_{m}_*"),
            })
    entries.append({"name": "Time-MoE-ZS",
                    "result_dir": "fm_time_moe_xmeas10_zeroshot_test"})
    entries.append({"name": "Sundial-ZS",
                    "result_dir": "fm_sundial_xmeas10_zeroshot_test"})
    entries.append({"name": "Timer-XL-raw",
                    "result_dir": one_dir(
                        f"forecast_TEP_IDV13_XMEAS10_5var_raw_few_{ratio}_timer_xl_*")})
    # last two entries are highlighted in the radar plot
    entries.append({"name": "Timer-XL-diff",
                    "result_dir": one_dir(
                        f"forecast_TEP_IDV13_XMEAS10_5var_diff_few_{ratio}_timer_xl_*")})
    entries.append({"name": "Gate",
                    "result_dir": f"ensemble_Gate_XMEAS10_{ratio}_test"})
    return entries


def write_yaml(ratio: str) -> None:
    cfg = {
        "params": {
            "target": TARGET,
            "limit_csv_path": str(LIMITS_CSV),
            "data_root": str(V5),
            "results_root": "./results",
            "seq_len": 96,
            "pred_len": 96,
            "eval_steps": 15,
            "input_clean_steps": 30,
            "alarm_quality_rmse_factor": 0.2,
        },
        "test": [run_csv(9).name, run_csv(10).name],
        "model_dirs": model_dirs(ratio),
    }
    out = TSFM / "setting" / f"batch_metrics_tep_xmeas10_{ratio}.yaml"
    out.write_text(
        "# Auto-generated by scripts/adaptation/xmeas10/gen_batch_metrics_cfgs.py\n"
        "# Window-level (Category C) prognosis metrics, XMEAS10 few-shot "
        f"ratio {ratio}.\n" + yaml.safe_dump(cfg, sort_keys=False))
    print(f"wrote {out.name}  ({len(cfg['model_dirs'])} models)")


if __name__ == "__main__":
    write_limits()
    for r in RATIOS:
        write_yaml(r)
